### ISSUE TITLE
How to execute a command?

### ISSUE THREAD

**Issue by csteinlehner** [oh-my-fish/plugin-osx#8]
Hi, I'am totally new to oh-my-fish, so sorry if this ist totally stupid. But how can I execute a osx command in the shell?

The Plugin is installed (listed under omf list), but the commands like 'dbf' just get me "fish: Unknown command 'dbf'".

**Comment by bobthecow** [comment]
There isn't a `dbf` command in this plugin.

**Comment by csteinlehner** [comment]
sorry, of course `cdf` 
none of the commands work.

**Comment by csteinlehner** [comment]
just tested it again. sorry everything works.

**Comment by bobthecow** [comment]
Heh. Glad you got it sorted. 

Was it something to do with autoloading or needing to start a new shell after installing or something?

**Comment by csteinlehner** [comment]
Yes, looks like I didn't start a new session, thought I did this.
